export const testVariable = 'test-variable'
export const NEXT_APP_BASE_URL = "https://apimenudev.talabatmenu.com"
export const TEMP_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIiLCJzdXBwbGllcklkIjoiNjNkMzI1ZTcwNzBjNjg4M2Y4ZDNiODA4Iiwicm9sZUlkIjoiNjNmMGViYWIxMWZhZWQ5ODM5Zjc2N2I5IiwiaWF0IjoxNjkwNDY4NDY2fQ.kBgimtWhi4RS5-ObTSCO-DjOeHMLr3uvs-SkZ_tXMx0"
